// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkJmnIcxqavBiNP29ZN-mlWA6SJE5E24w',
    appId: '1:628384876063:web:4e8b8993bce6c3d4c4f72a',
    messagingSenderId: '628384876063',
    projectId: 'bellaradb',
    authDomain: 'bellaradb.firebaseapp.com',
    databaseURL: 'https://bellaradb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bellaradb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJdZwYm6HFYi4JDsFn7M-kzbTFzjeYcA',
    appId: '1:628384876063:android:3890c4e6d154b8f5c4f72a',
    messagingSenderId: '628384876063',
    projectId: 'bellaradb',
    databaseURL: 'https://bellaradb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bellaradb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD44oessDIkj-anjbf7tDScHZDnsWHix7M',
    appId: '1:628384876063:ios:c9ad5b39ee9966d5c4f72a',
    messagingSenderId: '628384876063',
    projectId: 'bellaradb',
    databaseURL: 'https://bellaradb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bellaradb.appspot.com',
    iosClientId: '628384876063-g3id90jhta87ri6e36jumd5l66mc89r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellaraa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD44oessDIkj-anjbf7tDScHZDnsWHix7M',
    appId: '1:628384876063:ios:eef2a0ca6f7f0d75c4f72a',
    messagingSenderId: '628384876063',
    projectId: 'bellaradb',
    databaseURL: 'https://bellaradb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bellaradb.appspot.com',
    iosClientId: '628384876063-m2ondeeo4269543to75ejcvg2qt0t0nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellaraa.RunnerTests',
  );
}
